### PR TITLE
Support config file and keyring

### PR DESCRIPTION
**Pull request by bdrung**
This pull requests merges all my local _improvements_ into this module. It is stacked on the pull request #62 which should be reviewed and merged before this one. Following changes are included:

* Add `profitbricks.utils` containing helper functions: `ask()` and `find_item_by_name`
* Add `ProfitBricksService.get_datacenter_by_name()`
* Implement `ProfitBricksService.wait_for_completion()`
* Support providing a client user agent
* Add config file and keyring support
* Add pb-api-shell script to examples

Please review these changes carefully and tell me if you are happy to merge them or if you like to have it implemented differently.

### CODE REVIEW

**Comment by bdrung** [comment]
Since pull request #62 was merge, I rebased this set of patches. Please review them.

**Comment by nurfet-becirevic** [comment]
@bdrung, I can't run the tests. Missing `configparser` module.
```
python -m unittest discover tests test_datacenter.py
E
======================================================================
ERROR: test_datacenter (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_datacenter
Traceback (most recent call last):
  File "c:\python27\Lib\unittest\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "c:\python27\Lib\unittest\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "C:\workspace\virtualenvs\pbpythonsdk\repo\profitbricks-sdk-python\tests\test_datacenter.py", line 19, in <module>
    from profitbricks.client import Server, Volume
  File "profitbricks\client.py", line 16, in <module>
    import configparser
ImportError: No module named configparser
```

**Comment by bdrung** [comment]
The code worked on Python 3. In Python 2 the module is called `ConfigParser` instead of `configparser`. I changed the patch to work with Python 2 and 3:

```python
try:
    import configparser
except ImportError:
    import ConfigParser as configparser
```

**Comment by jasmingacic** [comment]
@bdrung I would like to revisit this. I'm going to leave some remarks in the code.

**Pull request merged**
